name: gwt-standortkarte

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    env:
      DOCKER_ACCOUNT: pfeimich
      DOCKER_REPO: standortkarte
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      BUILD_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - uses: actions/checkout@v1
      - name: Build inside Docker Container and create final Docker Image
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker pull $DOCKER_ACCOUNT/$DOCKER_REPO:latest
          docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -f Dockerfile.native-build .
          docker tag $DOCKER_ACCOUNT/$DOCKER_REPO:latest $DOCKER_ACCOUNT/$DOCKER_REPO:2.0.$BUILD_NUMBER
      - name: Push Docker Images
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker images
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:latest
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:2.0.$BUILD_NUMBER
